declare module 'json-pointer'
declare module 'jsonld-signatures'
declare module '@digitalbazaar/ecdsa-multikey'
declare module '@digitalbazaar/ecdsa-sd-2023-cryptosuite'
declare module '@digitalbazaar/data-integrity'